// Quick local test: generate a PDF with mock data and write to disk
import { writeFile } from "fs/promises";

// We need to use tsx to run TypeScript with path aliases, so let's use dynamic import
const { generateProposalPdf } = await import("./src/lib/pdf/generate-pdf.ts");

const mockData = {
  title: "Test Building Automation Project",
  clientName: "Portland General Hospital",
  clientAddress: "1234 SW Main St, Portland, OR 97201",
  projectLabel: "RESPONSE TO RFP",
  coverTemplate: "no_photo",
  logoUrl: "/images/hms_logo.png",
  companyName: "HMS Commercial Service, Inc.",
  companyAddress: "123 Industry Way, Portland, OR",
  companyPhone: "(503) 555-0100",
  companyEmail: "info@hmscommercial.com",
  companyWebsite: "www.hmscommercial.com",
  sections: [
    { slug: "cover_page", displayName: "Cover Page", content: {}, isEnabled: true },
    { slug: "table_of_contents", displayName: "Table of Contents", content: {}, isEnabled: true },
    { slug: "introduction", displayName: "Introduction", content: { body: "<p>HMS Commercial Service is pleased to present this proposal for building automation services.</p><p>We have extensive experience in healthcare facility controls and look forward to partnering with Portland General Hospital.</p>" }, isEnabled: true },
    { slug: "firm_background", displayName: "Firm Background & Experience", content: { narrative: "<p>HMS Commercial Service has been providing building automation solutions since 1995. We specialize in healthcare, education, and commercial facilities.</p><h3>Our Approach</h3><p>We deliver turnkey solutions from design through commissioning.</p>" }, isEnabled: true },
    { slug: "key_personnel", displayName: "Key Personnel & Org Chart", content: { org_chart_mode: "upload", org_chart_image: "/images/hms_org_chart.png" }, isEnabled: true },
    { slug: "executive_summary", displayName: "Executive Summary", content: { body: "<p>This proposal outlines our comprehensive approach to modernizing the building automation system at Portland General Hospital.</p>" }, isEnabled: true },
    { slug: "project_schedule", displayName: "Project Schedule", content: { output_mode: "ai_only", execution_strategy: { project_duration: "6 months", approach_narrative: "Our phased approach minimizes disruption to hospital operations.", phases: [{ name: "Design & Engineering", duration: "6 weeks", description: "Complete system design and submittal preparation", milestones: ["Design review meeting", "Submittal package complete"] }, { name: "Installation", duration: "12 weeks", description: "Phased installation across hospital wings", milestones: ["Wing A complete", "Wing B complete", "Wing C complete"] }], critical_path: ["Equipment procurement", "Network infrastructure", "BMS programming"] } }, isEnabled: true },
    { slug: "site_logistics", displayName: "Site Logistics & Safety", content: { body: "<p>HMS maintains a comprehensive safety program. All personnel are OSHA 10 certified.</p>" }, isEnabled: true },
    { slug: "qaqc_commissioning", displayName: "QA/QC/Commissioning", content: { quality_assurance: "<p>Our QA program ensures all work meets specifications.</p>", quality_control: "<p>Point-to-point verification of every device.</p>", commissioning: "<p>Full functional performance testing.</p>" }, isEnabled: true },
    { slug: "reference_check", displayName: "Reference Check", content: {}, isEnabled: true },
    { slug: "project_cost", displayName: "Project Cost", content: {}, isEnabled: true },
  ],
  personnel: [
    { fullName: "Troy Hartfeil", title: "Owner", roleType: "Project Executive", yearsIndustry: 25, yearsCompany: 25, yearsWithDistech: 15, taskDescription: null, specialties: ["BAS Design", "Project Management"], certifications: ["Distech Certified"], bio: "<p>Troy founded HMS in 1995 and oversees all operations.</p>" },
    { fullName: "Cody Gormley", title: "Controls Division Manager", roleType: "Project Manager", yearsIndustry: 12, yearsCompany: 8, yearsWithDistech: 8, taskDescription: null, specialties: ["Healthcare Controls", "Commissioning"], certifications: ["Distech Certified", "OSHA 30"], bio: "<p>Cody manages the controls division and leads complex healthcare projects.</p>" },
    { fullName: "Drew Davis", title: "Controls Operations Mgr", roleType: "Field Lead", yearsIndustry: 10, yearsCompany: 6, yearsWithDistech: 6, taskDescription: null, specialties: ["Programming", "Networking"], certifications: ["Niagara N4"], bio: null },
  ],
  caseStudies: [
    { projectName: "City of Hillsboro Civic Center DDC Upgrade", clientName: "City of Hillsboro", buildingType: "Government", squareFootage: 168436, photoUrl: "https://nhtuwnwctpelmszxkuor.supabase.co/storage/v1/object/public/project-photos/b8fc0ebd-eff6-4f71-9c54-1983b5fef45a/1772209928090-m9zbbtzx9w.jpg", narrative: "HMS Commercial Service successfully completed a comprehensive building automation system (BAS) controls upgrade at the City of Hillsboro Civic Center to improve system reliability, operational efficiency, and long-term maintainability of the facility. The project scope included the modernization of the existing controls infrastructure, integration with the City's enterprise-level BAS, and standardization of programming across all controlled equipment. All engineering, installation, programming, and commissioning were performed in-house by HMS personnel, ensuring continuity between design intent, field execution, and final system performance. HMS worked closely with the City of Hillsboro's facilities and IT teams to integrate the upgraded controls into the existing enterprise server environment. This approach allowed the City to maintain centralized monitoring, trending, and alarming while minimizing disruption to ongoing operations. Careful coordination ensured compliance with City IT standards and cybersecurity requirements. During construction, HMS maintained continuous system operation where required, phasing the work to avoid occupant impact and maintain critical building functions. Following installation, HMS completed full point-to-point verification, functional performance testing, and system optimization to confirm proper operation under all modes. The project concluded with the delivery of accurate as-built documentation, standardized control sequences, and operator training to support long-term system ownership. The completed upgrade provides the City of Hillsboro with a scalable, reliable, and user-friendly BAS platform that enhances visibility into building performance and supports future expansion." },
    { projectName: "City of Hillsboro Intermodal Transit Facility", clientName: "City of Hillsboro", buildingType: "Government", squareFootage: 269000, photoUrl: "https://nhtuwnwctpelmszxkuor.supabase.co/storage/v1/object/public/project-photos/b8fc0ebd-eff6-4f71-9c54-1983b5fef45a/1772212393292-kyhjyj7vv4.jpg", narrative: "HMS Commercial Service successfully completed a direct digital control (DDC) retrofit at the City of Hillsboro Intermodal Transit Facility to modernize the existing building automation system and improve overall system reliability, performance, and maintainability. The project scope included the replacement and upgrade of legacy control components, reprogramming of HVAC control sequences, and integration of the new DDC system into the City's existing enterprise-level building automation platform. All engineering, installation, programming, and commissioning were performed in-house by HMS personnel, ensuring alignment between design intent, field execution, and final system operation. HMS coordinated closely with the City of Hillsboro's facilities and IT teams to ensure seamless integration with the City's enterprise server, providing centralized monitoring, scheduling, trending, and alarming consistent with City standards. Special attention was given to maintaining system continuity and minimizing operational disruptions within this active, publicly occupied transit facility. The retrofit work was carefully phased to maintain critical building functions throughout construction. Upon completion, HMS conducted comprehensive point-to-point verification, functional performance testing, and system optimization to confirm proper operation across all modes and occupancy conditions. The project concluded with the delivery of accurate as-built documentation, standardized programming, and operator training to support long-term system ownership. The completed DDC retrofit provides the City of Hillsboro with a modern, scalable, and reliable building automation system that enhances visibility into building performance and supports efficient operation of the Intermodal Transit Facility." },
    { projectName: "City of Hillsboro Year Round Shelter", clientName: "City of Hillsboro", buildingType: "Government", squareFootage: null, photoUrl: "https://nhtuwnwctpelmszxkuor.supabase.co/storage/v1/object/public/project-photos/b8fc0ebd-eff6-4f71-9c54-1983b5fef45a/1772212031556-np7cetvysck.jpg", narrative: "HMS Commercial Service successfully completed the building automation system (BAS) controls scope for the City of Hillsboro Year Round Shelter new construction project. The controls system was designed and implemented to provide reliable, efficient, and maintainable operation of the facility's mechanical systems while supporting the City's long-term operational standards. The project included complete in-house engineering, installation, programming, and commissioning of the BAS by HMS personnel. This unified approach ensured consistency between design intent, field installation, and final system operation, resulting in a high-quality and reliable controls installation. Throughout construction, HMS collaborated with the general contractor and mechanical trades to align controls installation with the overall project schedule and commissioning activities. Upon completion, HMS performed full point-to-point checkout, functional performance testing, and system optimization to verify proper operation under all modes and occupancy conditions. The project concluded with the delivery of complete as-built documentation, standardized control programming, and operator training to ensure a smooth transition to City operations. The finished BAS provides the City of Hillsboro with a scalable, dependable controls platform that supports occupant comfort, energy efficiency, and long-term facility management for the Year Round Shelter." },
    { projectName: "City of Hillsboro Main Fire Station", clientName: "City of Hillsboro", buildingType: "Government", squareFootage: 18000, photoUrl: "https://nhtuwnwctpelmszxkuor.supabase.co/storage/v1/object/public/project-photos/b8fc0ebd-eff6-4f71-9c54-1983b5fef45a/1772212692229-h3m14fb82lm.jpg", narrative: "HMS Commercial Service successfully completed a direct digital control (DDC) retrofit at the City of Hillsboro Main Fire Station to modernize the building automation system while maintaining continuous operation of this mission-critical public safety facility. The project scope included the replacement of legacy control hardware, modernization of HVAC control sequences, and integration of the upgraded DDC system into the City's enterprise building automation platform. All engineering, installation, programming, and commissioning were performed in-house by HMS personnel, ensuring consistency between design intent, field execution, and final system performance. HMS coordinated closely with the City of Hillsboro's facilities, IT, and fire department staff to phase the retrofit work in a manner that preserved uninterrupted building operation, indoor air quality, and occupant comfort for 24/7 emergency response functions. Particular attention was given to reliability, redundancy, and alarm functionality to support the operational requirements of a fire station environment. Upon completion of installation, HMS performed comprehensive point-to-point verification, functional performance testing, and system optimization to validate proper operation under all modes and occupancy conditions. Integration with the City's enterprise server provides centralized monitoring, trending, scheduling, and alarming consistent with City standards. The project concluded with delivery of complete as-built documentation, standardized programming, and operator training to ensure long-term system reliability and ease of maintenance. The completed DDC retrofit provides the City of Hillsboro with a modern, scalable, and dependable controls platform that supports the critical operational needs of the Main Fire Station." },
    { projectName: "City of Hillsboro Public Works Fleet Building", clientName: "City of Hillsboro", buildingType: "Government", squareFootage: 15000, photoUrl: "https://nhtuwnwctpelmszxkuor.supabase.co/storage/v1/object/public/project-photos/b8fc0ebd-eff6-4f71-9c54-1983b5fef45a/1772213191111-pt157pk4fbd.jpg", narrative: "HMS Commercial Service successfully completed a direct digital control (DDC) retrofit and controls scope associated with a building addition at the City of Hillsboro Public Works Fleet Building. The project modernized the existing building automation system while extending controls coverage to new mechanical systems serving the facility expansion. The project scope included replacement of legacy control hardware, reprogramming and standardization of HVAC control sequences, and installation of new DDC controls for equipment serving the addition. All engineering, installation, programming, and commissioning were performed in-house by HMS personnel, ensuring consistency across the existing facility and new construction. HMS coordinated closely with the City of Hillsboro's facilities, IT, and Public Works staff to phase the retrofit work around ongoing fleet operations, maintaining continuous functionality of critical maintenance and support spaces. Integration with the City's enterprise building automation platform provides centralized monitoring, scheduling, trending, and alarming consistent with City standards. Upon completion, HMS conducted full point-to-point verification, functional performance testing, and system optimization for both the existing building and the new addition. Special attention was given to system reliability, ventilation control, and temperature regulation to support fleet maintenance activities and occupant safety. The project concluded with delivery of accurate as-built documentation, standardized programming, and operator training to support long-term system ownership. The completed DDC retrofit and addition controls provide the City of Hillsboro with a scalable, reliable building automation system that supports efficient operation and future expansion of the Public Works Fleet Building." },
  ],
  references: [
    { contactName: "John Smith", title: "Facilities Director", company: "Providence Health", phone: "(503) 555-0200", email: "jsmith@providence.org", category: "Healthcare" },
    { contactName: "Jane Doe", title: "Project Manager", company: "Fortis Construction", phone: "(503) 555-0300", email: "jdoe@fortis.com", category: "General Contractor" },
  ],
  costData: {
    columns: [
      { id: "base", name: "Base Bid", type: "base" },
      { id: "alt1", name: "Alternate 1", type: "alternate" },
    ],
    rows: [
      { id: "r1", description: "BAS Installation - Wing A", values: { base: "$125,000", alt1: "$15,000" } },
      { id: "r2", description: "BAS Installation - Wing B", values: { base: "$98,000", alt1: "$12,000" } },
      { id: "r3", description: "Programming & Commissioning", values: { base: "$45,000", alt1: "$8,000" } },
    ],
    notes: "All prices include labor and materials. Tax not included.",
  },
  emrRatings: [
    { year: 2022, rating: 0.82 },
    { year: 2023, rating: 0.79 },
    { year: 2024, rating: 0.75 },
  ],
};

console.log("Generating PDF...");
const start = Date.now();
const pdfBytes = await generateProposalPdf(mockData);
const elapsed = ((Date.now() - start) / 1000).toFixed(1);
console.log(`PDF generated in ${elapsed}s (${pdfBytes.length} bytes)`);

await writeFile("test-output.pdf", pdfBytes);
console.log("Written to test-output.pdf — open it to verify!");
